# A basic codemagic.yaml file for Ionic Capacitor (Android)

workflows:
  ionic-android:
    name: Ionic Android
    instance_type: mac_mini_m1
    environment:
      node: 20.10.0
      java: 21
      # --- THIS IS NEW ---
      groups:
        - keystore_credentials # This loads all the secrets you just made
        
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Build Ionic app
        script: | 
          npm run build
      - name: Sync to Capacitor
        script: | 
          npx cap add android
          npx cap sync android
  
# --- ADD THIS NEW SECTION HERE ---
      - name: Update Version Code (Brute Force)
        script: | 
          # This finds "versionCode X" in the file and replaces it with your Codemagic build number + 100
          sed -i '' "s/versionCode [0-9]*/versionCode $((BUILD_NUMBER + 100))/g" android/app/build.gradle
          echo "Updated version code to $((BUILD_NUMBER + 100))"          
          
      # --- THIS SCRIPT IS NEW ---
      - name: Set up keystore
        script: | 
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks

      # --- THIS SCRIPT IS MODIFIED ---
      - name: Build Android App Bundle
        script: | 
          cd android
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=/tmp/keystore.jks \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
            
    artifacts:
      - android/app/build/outputs/bundle/release/app-release.aab
